### ISSUE TITLE
Invaid command spl

### ISSUE THREAD

**Issue by Butrdtost** [Thore-Krug/Flash-CHIP#12]
I don't know why but it's telling me

 Installing CHIP-tools
Already up-to-date.
== Server selected ==
== preparing images ==
== Local/cached probe files located ==
== Staging for NAND probe ==
Image Name:   detect NAND
Created:      Sat Sep  7 05:08:33 2019
Image Type:   ARM Linux Script (uncompressed)
Data Size:    97 Bytes = 0.09 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 89 Bytes = 0.09 kB = 0.00 MB
waiting for fel...OK
Invalid command spl

and won't go any further.

**Comment by Nachip-blip** [comment]
I think this problem occured because sunxi-tools doesn't include sunxi-nand-image-builder or something like that, if you use apt-get install. It's apparently possible to still get it if you build it using make misc. I used only the relevant info (sunxi-tools) from the following link to get the missing file installed as well. Since I had already installed it the usual way before hand, it did give me "file already exists" a few times, but not for the missing file. 

http://www.chip-community.org/index.php/Flashing_Buildroot_Image_from_Ubuntu

After that, I just used this script.
